# ─── Basic Colors ─────────────────────────────────────
foreground              #dcd7ba
background              #1f1f28
selection_foreground    #1f1f28
selection_background    #2a2a37

# ─── Cursor ───────────────────────────────────────────
cursor                  #c8c093
cursor_text_color       #1f1f28

# ─── Borders / Decorations ────────────────────────────
active_border_color     #c8c093
inactive_border_color   #727169
wayland_titlebar_color  #1f1f28

# ─── Marked text ──────────────────────────────────────
mark1_foreground        #1f1f28
mark1_background        #957fb8
mark2_foreground        #1f1f28
mark2_background        #7fb4ca
mark3_foreground        #1f1f28
mark3_background        #a3d4d5

# ─── 16-Color Palette ─────────────────────────────────

# black
color0  #090618
color8  #727169

# red
color1  #c34043
color9  #e82424

# green
color2  #76946a
color10 #98bb6c

# yellow
color3  #c0a36e
color11 #e6c384

# blue
color4  #7e9cd8
color12 #7fb4ca

# magenta
color5  #957fb8
color13 #938aa9

# cyan
color6  #6a9589
color14 #7aa89f

# white
color7  #c8c093
color15 #dcd7ba
