source = ~/.config/hypr/configs/monitors.conf
source = ~/.config/hypr/configs/autostart.conf
source = ~/.config/hypr/configs/env.conf
source = ~/.config/hypr/configs/hyprcolors.conf
source = ~/.config/hypr/configs/animations.conf
source = ~/.config/hypr/configs/general.conf
source = ~/.config/hypr/configs/input.conf
source = ~/.config/hypr/configs/keybinds.conf
source = ~/.config/hypr/configs/windowrule.conf
source = ~/.config/hypr/configs/debug.conf
source = ~/.config/hypr/environment.conf

exec-once = pkill mpvpaper
exec-once = sleep 2 && mpvpaper eDP-1 ~/Videos/girls_white.mp4
