# Variables
$inFocusOpacity = 0.9
$notInFocusOpacity = 0.7

# Ignore maximize requests from apps. You'll probably like this.
# (line6) ... suppressEvent ...

# Fix some dragging issues with XWayland
# windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# Opacity rules
windowrulev = opacity $inFocusOpacity $notInFocusOpacity,title:^.*().*$,
windowrulev = opacity 1 1, class:^(waybar)$
windowrulev = opacity 1,class:.*(kitty).*$,
windowrulev = fullscreen, class:^(Lunar Client.*)$
windowrulev = tile, class:^(Lunar Client.*)$
windowrulev = opacity $inFocusOpacity $notInFocusOpacity,class:^(firefox|brave|chromium|librewolf|qutebrowser|zen-browser)$,
windowrulev = opacity $inFocusOpacity $notInFocusOpacity,title:^.*(Spotify).*$,
windowrulev = opacity $inFocusOpacity $notInFocusOpacity,title:^.*(Discord).*$,
windowrulev = opacity $inFocusOpacity $notInFocusOpacity,title:^.*(Telegram).*$,
windowrulev = opacity $inFocusOpacity $notInFocusOpacity,title:^.*(Code).*$,
windowrulev = opacity $inFocusOpacity $notInFocusOpacity,title:^.*(Thunar|nemo).*$,
